#!/bin/sh

if which urxvt >/dev/null >&1; then
	OPTS=urxvt
	SKIP='-mesg'
else
	SKIP=
	OPTS='xterm +ah -aw -b 0 -bw 0 +vb +nul -pc +pob -s -si -sk +t'
fi

while [ $# != 0 ]; do
	case "$1" in
	($SKIP)                                shift 1;;
	(-T|-title) OPTS="$OPTS -title    $2"; shift 2;;
	(-N|-name)  OPTS="$OPTS -name     $2"; shift 2;;
	(-*)        break; ;;
	(*)         OPTS="$OPTS -e"; break; ;;
	esac
done

exec $OPTS "$@"
