#! /bin/sh

set -eu


##
## Usage
##
usage () {
	cat <<EOF
usage: $0 [ <options> ] [ <files> ]
<options>:
  -f  Update files in current directory from configuration files in home.
  -t  Update configuration files from files in current directory; make backups.
  -T  Like ‘-t’ but don’t make any backups.
  -y  Assume ‘y’ to all questions, i.e. overwrite any changed files w/o asking.
  -n  Assume ‘n’ to all questions, i.e. only copy new files; leave existing be.
EOF
	exit 1
}


##
## Parse arguments
##
direction=
ask=ask

for arg in "$@"; do
	case $arg in
	-)   usage;;
	-?*) :    ;;
	*)   break
	esac
	shift
	while arg=${arg#?}; [ -n "$arg" ]; do
		case "$arg" in
		f*) direction=from   ; backup=false;;
		t*) direction=to     ; backup=true ;;
		T*) direction=to     ; backup=false;;
		y*) ask=if_different ;;
		n*) ask=false        ;;
		*)  usage            ;;
		esac
	done
done


##
## Color handling
##
if ! which tput >/dev/null 2>&1; then
	tput () {
		return 0
	}
fi


##
## Print info
##

case "$direction" in
from)
	tput bold
	tput setaf 7
	echo 'Updating files in current directory from configuration files'
	tput sgr0
	;;
to)
	tput bold
	tput setaf 7
	echo 'Updating configuration files from files in current directory'
	tput sgr0
	;;
*)
	usage
esac


##
## File arguments
##
if [ $# -eq 0 ]; then
	match () {
		return 0
	}
else
	match () {
		for f in "$@"; do
			case "$file" in "$f")
				return 0
			esac
		done
		return 1
	}
fi


##
## Interactive asking
##
if diff=$(which cdiff 2>&1); then
	cdiff=$diff
else
	diff=diff
	cdiff=cat
fi

equal() {
	set -- "$@" "$(readlink "$2")" "$(readlink "$3")"

	if [ x"$4" = x"$5" ]; then
		if [ -n "$4" ] || cmp -s "$2" "$3"; then
			return 0
		fi
	fi

	if [ x"$1" != x-v ]; then
		return 1
	elif [ -z "$4$5" ]; then
		"$diff" -u -- "$3" "$2"
		return 1
	fi

	(
		printf '%s\n' "--- $3"
		printf '%s\n' "+++ $2"

		if [ -z "$5" ]; then
			sed s/^/-/ <$3
		else
			printf %s\\n "-→ $5"
		fi

		if [ -z "$4" ]; then
			sed s/^/+/ <$2
		else
			printf %s\\n "+→ $4"
		fi
	) | "$cdiff"
	return 1
}

ask() {
	if equal -v "$1" "$2"; then
		return 1
	fi

	while :; do
		tput bold
		tput setaf 7
		tput setab 4
		printf '%s:' "$2"
		tput sgr0
		tput setaf 7
		tput setab 4
		printf ' [yn] '
		tput sgr0
		read answer || exit 0
		case "$answer" in
		[yY]) return 0 ;;
		[nN]) return 1 ;;
		esac
	done
}

if_different() {
	! equal -s "$1" "$2"
}


##
## Emacs files handling
##
compile_el() {
	if [ -n "$(which emacs 2>/dev/null)" ]; then
		tput bold
		tput setaf 7
		echo "Compiling $1"
		tput sgr0
		emacs --batch -f batch-byte-compile "$1"
	fi
}


##
## Do the job
##
handle() {
	case $3 in \~*)    set -- "$1" "$2" "$HOME${3#?}"; esac
	case $3 in *@)     set -- "$1" "$2" "${3%@}${2##*/}"; esac
	case $3 in */.|*/) set -- "$1" "$2" "$3$2"; esac

	case $1 in from)
		[ -d "${3%/*}" ] || return 0
		set -- "$1" "$3" "$2"
	esac

	if [ -h "$3" ] || [ -e "$3" ]; then
		if ! $ask "$2" "$3" <&3; then
			return 0
		elif $backup; then
			mv -- "$3" "$3~"
		fi
	fi

	mkdir -p -- "${3%/*}"
	cp -dv -- "$2" "$3"

	case "$direction:$3" in to:*.el)
		compile_el "$3"
	esac
}

while read pattern destination; do
	for file in $pattern; do
		case "$file" in *\~|\#*|*\#|.*)
			continue
		esac
		if ! match "$@"; then
			:
		elif [ -h "$file" ] || [ -f "$file" ]; then
			handle "$direction" "$file" "$destination"
		elif ! [ -e "$file" ]; then
			echo "update: $file: missing, skipping" >&2
		fi
	done
done 3<&1 <<EOF
emacs/*            ~/.emacs.d/@
mail/*             ~/.mail/@
git/*              ~/.config/git/@
inputrc            ~/.
irssi.theme        ~/.irssi/mina.theme
sawfishrc          ~/.sawfish/rc
statuses           ~/.irssi/
bin/*              ~/.local/
libexec/*          ~/.local/
sh/*               ~/.@
vimperatorrc       ~/.vimperator/rc
x/Xresources       ~/.config/@
x/gtkrc-2.0        ~/.@
x/gtk-3.0.ini      ~/.config/gtk-3.0/settings.ini
x/xinitrc          ~/.@
x/xsettingsd       ~/.@
x/xserverrc        ~/.@
x/local.keymap     ~/.config/xkb/keymap/local
x/local.symbols    ~/.config/xkb/symbols/local
x/80-char.png      ~/.urxvt/@
EOF
