#!/bin/sh

playing_file=$(umask 077; mktemp)
trap 'rm -f -- "$playing_file"' 0

if m pause-maybe; then
	exec ln -sf ~/.local/bin/m "$playing_file"
fi &

sleep 0.1

if [ -x ~/.local/libexec/slock ]; then
	~/.local/libexec/slock
elif [ -x /usr/bin/slock ]; then
	slock
else
	xlock -mode blank -bg black -fg gray3
fi

set -- toggle
. "$playing_file"
