#!/bin/sh

xset -b -c r rate 250 50 s off +dpms

layout=pl,pl
variant=dvp,
options=ctrl:nocaps,grp:shifts_toggle,grp_led:scroll,nbsp:level3n,compose:lctrl-altgr,compose:rctrl-algtgr

dir=$HOME/.config/xkb
if [ -e $dir/symbols/local ]; then
	layout=local,pl
	setxkbmap -I"$dir" -print "$layout" "$variant" "$options" \
	          >$dir/keymap/local
	xkbcomp -w0 -I"$dir" "$dir/keymap/local" "$DISPLAY"
else
	setxkbmap "$layout" "$variant" "$options"
fi
