#!/bin/sh
## .xinitrc  -- X init script
## Copyright 2008-2017 by Michal Nazarewicz <mina86@mina86.com>

set -u

has() {
	which "$1" >/dev/null 2>&1
}

exec_xset() {
	exec xset -b -c r rate 250 50 s off +dpms
}

init_screen() {
	if [ -e ~/bin/libexec/xscreen-config.pl ]; then
		tmp=$(mktemp)
		if perl -w ~/bin/libexec/xscreen-config.pl "$@" >$tmp; then
			sh -x -- "$tmp"
		fi
		rm -f -- "$tmp"
	fi
	unset tmp
	test -x ~/bin/set-bg && ~/bin/set-bg
}

init_kbd() {
	layout=pl,pl
	variant=dvp,
	options=ctrl:nocaps,grp:shifts_toggle,grp_led:scroll,nbsp:level3n,compose:lctrl-altgr,compose:rctrl-algtgr

	dir=$HOME/.config/xkb
	if [ -e "$dir/symbols/local" ]; then
		layout=local,pl
		setxkbmap -I"$dir" -print >$dir/keymap/local \
		          "$layout" "$variant" "$options"
		xkbcomp -w0 -I"$dir" "$dir/keymap/local" $DISPLAY
	else
		setxkbmap "$layout" "$variant" "$options"
	fi

	unset dir layout variant options
}

gkrellm_maybe() {
	[ -f "$1" ] && shift && exec gkrellm "$@" &
}

start_gkrellm() {
	gkrellm_maybe ~/.gkrellm2/user-config
	for file in ~/.gkrellm2/user-config_S-*; do
		gkrellm_maybe "$file" -s "${file##*/user-config_S-}"
	done
	unset file
}

exec_background_tasks() {
	spawn() {
		has "$1" && exec "$@" &
	}

	cd /
	init_kbd
	spawn xsettingsd
	spawn xcompmgr
	test -e ~/.config/redshift.conf && spawn redshift
	has gkrellm && start_gkrellm
	exec_xset
}

start_wm() {
	cd ~
	if ! has sawfish; then
		echo '!!!'
		echo '!!! Sawfish not found; running xterm instead.'
		echo '!!!'
		xterm
	# elif ssh-add -l >/dev/null 2>&1; then
	#	sawfish
	elif has ssh-agent; then
		ssh-agent sawfish
	elif has gpg-agent; then
		gpg-agent --daemon sawfish
	else
		sawfish
	fi
}

exec_quit_cmd() {
	if test -s "$1" && read cmd <$1; then
		case "$cmd" in
		poweroff|reboot)
			exec /sbin/$cmd
			;;
		reboot-w)
			exec /usr/local/sbin/reboot-w
		esac
	fi
	exit 0
}

exec_x() {
	[ -f ~/.config/Xresources ] && xrdb -merge ~/.config/Xresources
	init_screen
	exec_background_tasks &

	tmp=$(mktemp)
	trap 'rm -f -- "$tmp"' 0
	SAWFISH_QUIT_CMD_FILE=$tmp start_wm
	exec_quit_cmd "$tmp"
}

main() {
	case ${1-} in
	scr|screen)
		shift
		init_screen "$@"
		exec_xset
		;;
	kbd|key)
		shift
		init_kbd "$@"
		exec_xset
		;;
	'')
		exec_x "$@" >>/tmp/x-${USER-anonymous}@${DISPLAY-no-display}.log 2>&1
		;;
	*)
		echo "xinit: unrecognised subcommand: $1" >&2
		echo 'usage: xinit (screen | kbd)' >&2
		exit 1
	esac
}

main "$@"
