(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:background "black" :foreground "gray" :height 75 :width normal :foundry "adobe" :family "courier"))))
 '(Man-overstrike ((t (:foreground "#33CC33"))))
 '(Man-reverse ((t (:foreground "#CC3333"))))
 '(auto-dim-other-buffers-face ((t :background "#112222")))
 '(completions-common-part ((t (:inherit default :foreground "yellow"))))
 '(completions-first-difference ((t (:inherit default :foreground "cyan" :weight bold))))
 '(cursor ((t (:background "#FF0"))))
 '(custom-button ((t (:inherit widget-button))))
 '(custom-button-face ((t (:foreground "cyan"))))
 '(custom-documentation ((t (:foreground "yellow" :weight bold))))
 '(custom-documentation-face ((t (:foreground "yellow" :weight bold))))
 '(custom-group-tag ((t (:foreground "cyan" :underline t :weight bold))))
 '(custom-group-tag-face ((t (:foreground "cyan" :underline t :weight bold))))
 '(custom-variable-tag ((t (:inherit custom-link :underline nil))))
 '(custom-variable-tag-face ((t (:foreground "cyan" :underline t :weight bold))))
 '(custom-visibility ((t (:inherit link :underline nil))))
 '(diff-added ((t (:inherit diff-changed :foreground "green"))))
 '(diff-added-face ((t (:foreground "green" :weight bold))) t)
 '(diff-changed ((t (:foreground "yellow"))))
 '(diff-changed-face ((t (:foreground "yellow" :weight bold))) t)
 '(diff-context ((t nil)))
 '(diff-file-header ((t (:background "grey30" :weight bold))))
 '(diff-header ((t (:background "grey20"))))
 '(diff-indicator-added ((t (:inherit diff-added))))
 '(diff-refine-added ((t (:inherit diff-added :background "#006600"))))
 '(diff-refine-change ((t (:inherit diff-changed :background "#666600"))) t)
 '(diff-refine-removed ((t (:inherit diff-removed :background "#660000"))))
 '(diff-removed ((t (:inherit diff-changed :foreground "red"))))
 '(diff-removed-face ((t (:foreground "red" :weight bold))) t)
 '(erc-action-face ((t (:foreground "magenta" :slant italic))))
 '(fill-column-indicator ((t (:inherit shadow :foreground "#333366"))))
 '(font-lock-builtin-face ((t (:foreground "#99F"))))
 '(font-lock-comment-face ((t (:foreground "#0c0" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "aquamarine"))))
 '(font-lock-doc-face ((t (:inherit font-lock-comment-face :foreground "#CF0"))))
 '(font-lock-function-name-face ((t (:foreground "lightskyblue"))))
 '(font-lock-keyword-face ((t (:foreground "#0FF"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-string-face ((t (:foreground "lightsalmon"))))
 '(font-lock-type-face ((t (:foreground "palegreen"))))
 '(font-lock-variable-name-face ((t (:foreground "lightgoldenrod"))))
 '(font-lock-warning-face ((t (:foreground "pink" :weight bold))))
 '(form-feed-line ((t (:strike-through "#366"))))
 '(fringe ((t (:background "#112211"))))
 '(header-line ((t (:inherit mode-line :background "#006" :foreground "#FFF"))))
 '(help-argument-name ((t (:inherit font-lock-variable-name-face))))
 '(highlight ((t (:background "#060" :underline "#0F0"))))
 '(hl-line ((t (:background "#003"))))
 '(keywiz-right-face ((t (:foreground "green"))))
 '(lazy-highlight ((t (:background "paleturquoise4"))))
 '(link ((t (:foreground "#0CF" :underline t))))
 '(link-visited ((t (:inherit link :foreground "#96F"))))
 '(match ((t (:background "RoyalBlue3"))))
 '(mode-line ((t (:background "#009" :foreground "#FFF"))))
 '(mode-line-buffer-id ((t (:foreground "#9FF" :weight bold))))
 '(mode-line-highlight ((t (:background "#00F"))))
 '(mode-line-inactive ((t (:inherit mode-line :background "#333" :foreground "#CCC"))))
 '(notmuch-search-date ((t (:inherit notmuch-search-non-matching-authors))))
 '(notmuch-search-matching-authors ((t (:inherit default))))
 '(notmuch-search-non-matching-authors ((t (:inherit default :foreground "dim grey"))))
 '(notmuch-search-subject ((t (:inherit default :foreground "cyan"))))
 '(num3-face-even ((t (:foreground "#CFF"))))
 '(secondary-selection ((((type x-toolkit)) (:background "SkyBlue4")) (t (:inverse-video t))))
 '(tooltip ((t (:inherit variable-pitch :background "lightyellow" :foreground "black"))))
 '(whitespace-big-indent ((t (:inherit whitespace-tab :foreground "firebrick"))))
 '(whitespace-tab ((t (:background "grey22" :foreground "grey22"))))
 '(widget-button ((t (:background "#09F" :foreground "#000" :weight bold))))
 '(widget-button-face ((t (:background "blue" :foreground "cyan" :weight bold))) t)
 '(widget-field ((t (:background "blue"))))
 '(widget-field-face ((t (:background "blue"))) t))
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   '(ace-jump-mode apache-mode atomic-chrome auto-compile auto-dim-other-buffers bison-mode browse-kill-ring csv-mode easy-kill form-feed gitattributes-mode gitconfig-mode gitignore-mode gnu-elpa-keyring-update gnus-alias google-c-style haskell-mode lua-mode markdown-mode multiple-cursors notmuch num3-mode protobuf-mode rust-mode sed-mode shift-number typescript-mode)))
