(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "black" :foreground "gray" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 75 :width normal :foundry "adobe" :family "courier"))))
 '(auto-dim-other-buffers-face ((t :background "#112222")))
 '(completions-common-part ((t (:inherit default :foreground "yellow"))))
 '(completions-first-difference ((t (:inherit default :foreground "cyan" :weight bold))))
 '(custom-button ((t (:inherit widget-button))))
 '(custom-button-face ((t (:foreground "cyan"))))
 '(custom-documentation ((t (:foreground "yellow" :weight bold))))
 '(custom-documentation-face ((t (:foreground "yellow" :weight bold))))
 '(custom-group-tag ((t (:foreground "cyan" :underline t :weight bold))))
 '(custom-group-tag-face ((t (:foreground "cyan" :underline t :weight bold))))
 '(custom-variable-tag ((t (:foreground "cyan" :underline t :weight bold))))
 '(custom-variable-tag-face ((t (:foreground "cyan" :underline t :weight bold))))
 '(diff-added ((t (:inherit diff-changed :foreground "green"))))
 '(diff-added-face ((t (:foreground "green" :weight bold))) t)
 '(diff-changed ((t (:foreground "yellow"))))
 '(diff-changed-face ((t (:foreground "yellow" :weight bold))) t)
 '(diff-context ((t nil)))
 '(diff-file-header ((t (:background "grey30" :weight bold))))
 '(diff-header ((t (:background "grey20"))))
 '(diff-indicator-added ((t (:inherit diff-added))))
 '(diff-refine-added ((t (:inherit diff-added :background "#006600"))))
 '(diff-refine-change ((t (:inherit diff-changed :background "#666600"))) t)
 '(diff-refine-removed ((t (:inherit diff-removed :background "#660000"))))
 '(diff-removed ((t (:inherit diff-changed :foreground "red"))))
 '(diff-removed-face ((t (:foreground "red" :weight bold))) t)
 '(erc-action-face ((t (:foreground "magenta" :slant italic))))
 '(font-lock-builtin-face ((t (:foreground "#99F"))))
 '(font-lock-comment-face ((t (:foreground "#0c0" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "aquamarine"))))
 '(font-lock-doc-face ((t (:inherit font-lock-comment-face :foreground "#CF0"))))
 '(font-lock-function-name-face ((t (:foreground "lightskyblue"))))
 '(font-lock-keyword-face ((t (:foreground "#0FF"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-string-face ((t (:foreground "lightsalmon"))))
 '(font-lock-type-face ((t (:foreground "palegreen"))))
 '(font-lock-variable-name-face ((t (:foreground "lightgoldenrod"))))
 '(font-lock-warning-face ((t (:foreground "pink" :weight bold))))
 '(fringe ((t (:background "#112211"))))
 '(header-line ((t (:inherit mode-line :background "#006" :foreground "#FFF" :box nil))))
 '(help-argument-name ((t (:inherit font-lock-variable-name-face))))
 '(highlight ((t (:background "#060" :underline "#0F0"))))
 '(hl-line ((t (:background "#003"))))
 '(keywiz-command-face ((t (:foreground "cyan" :weight bold :height 1.2 :inherit (quote variable-pitch)))))
 '(keywiz-right-face ((t (:foreground "green"))))
 '(lazy-highlight ((t (:background "paleturquoise4"))))
 '(link ((t (:foreground "cyan" :underline t))))
 '(link-visited ((t (:inherit link :foreground "#96F"))))
 '(match ((t (:background "RoyalBlue3"))))
 '(mode-line ((t (:background "#009" :foreground "#FFF" :box nil))))
 '(mode-line-buffer-id ((t (:foreground "#9FF" :weight bold))))
 '(mode-line-highlight ((t (:background "#00F"))))
 '(mode-line-inactive ((t (:inherit mode-line :box nil :background "#333" :foreground "#CCC"))))
 '(notmuch-search-date ((t (:inherit notmuch-search-non-matching-authors))))
 '(notmuch-search-matching-authors ((t (:inherit default))))
 '(notmuch-search-non-matching-authors ((t (:inherit default :foreground "dim grey"))))
 '(notmuch-search-subject ((t (:inherit default :foreground "cyan"))))
 '(num3-face-even ((t (:foreground "#CFF" :underline nil :weight normal))))
 '(secondary-selection ((((type x-toolkit)) (:foreground nil :background "SkyBlue4")) (t (:foreground nil :background nil :inverse-video t))))
 '(tooltip ((t (:inherit variable-pitch :background "lightyellow" :foreground "black"))))
 '(whitespace-big-indent ((t (:inherit whitespace-tab :foreground "firebrick"))))
 '(whitespace-tab ((t (:background "grey22" :foreground "grey22"))))
 '(widget-button ((t (:foreground "#0FF" :underline "#099" :weight bold))))
 '(widget-button-face ((t (:background "blue" :foreground "cyan" :weight bold))) t)
 '(widget-field ((t (:background "blue"))))
 '(widget-field-face ((t (:background "blue"))) t))
